version: '3'

tasks:
  run:
    cmds:
      - go run cmd/main.go
    silent: true
  wire:
    cmds:
      - cd internal/di && wire
    silent: true
  test:
    cmds:
      - go test ./... -cover
    silent: true